import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth, ROLES } from '../auth.js';
import { asyncHandler } from '../utils.js';
import {
  availableReportsFor,
  defaultReportForUser,
  validateReportRequest
} from '../reports/config.js';

export const reportsRouter = Router();

const formatLabels = {
  screen: 'View on screen',
  csv: 'CSV',
  pdf: 'PDF'
};

function sanitizeFilters(filters = {}) {
  return Object.fromEntries(
    Object.entries(filters).filter(([, value]) => value !== undefined && value !== null && value !== '')
  );
}

function filterParams(filters = {}, user = {}) {
  return {
    start_date: filters.start_date || null,
    end_date: filters.end_date || null,
    organisation_id: filters.organisation_id || null,
    current_organisation_id: user.organisation_id || null,
    current_user_id: user.id || null
  };
}

function dateClause(alias, column = 'created_at') {
  return `(:start_date IS NULL OR DATE(${alias}.${column}) >= :start_date)
          AND (:end_date IS NULL OR DATE(${alias}.${column}) <= :end_date)`;
}

function cards(items) {
  return items.map(([label, value]) => ({ label, value: value ?? 0 }));
}

function section(title, rows, options = {}) {
  return {
    title,
    rows: rows || [],
    summary: { total_records: rows?.length || 0 },
    ...options
  };
}

function rowsToCsv(rows) {
  if (!rows?.length) return 'No records found';
  const headers = Object.keys(rows[0]);
  const escape = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;
  return [
    headers.join(','),
    ...rows.map((row) => headers.map((header) => escape(row[header])).join(','))
  ].join('\n');
}

function reportToCsv(report) {
  const blocks = [
    `# ${report.report_name}`,
    `Generated at,${report.generated_at}`,
    `Generated by,"${report.generated_by.name} (${report.generated_by.role})"`,
    '',
    '# Summary',
    rowsToCsv(report.summary_cards.map((card) => ({ metric: card.label, value: card.value }))),
    '',
    ...report.sections.map((item) => `# ${item.title}\n${rowsToCsv(item.rows)}`)
  ];
  return blocks.join('\n\n');
}

function csvPayload(report) {
  return {
    file_url: `data:text/csv;charset=utf-8,${encodeURIComponent(reportToCsv(report))}`,
    file_name: `${report.report_name.toLowerCase().replaceAll(' ', '-')}.csv`
  };
}

function printableValue(value) {
  return String(value ?? '').replace(/[^\x20-\x7E]/g, '?');
}

function escapePdfText(text) {
  return printableValue(text).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function formatReportDate(value, includeTime = false) {
  if (!value) return 'Not available';
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return printableValue(value);

  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    ...(includeTime ? { hour: 'numeric', minute: '2-digit', hour12: true } : {})
  }).format(date);
}

function humaniseKey(key) {
  return printableValue(key)
    .replaceAll('_', ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatRole(role) {
  return humaniseKey(role || '').replace('Ngo', 'NGO');
}

function formatReportValue(key, value) {
  if (value === null || value === undefined || value === '') return 'Not available';
  if (/date|_at$|submitted|registered|added|received|created/i.test(key)) {
    return formatReportDate(value, /_at$|submitted|generated/i.test(key));
  }
  if (/average.*hours/i.test(key) && Number(value) < 0) return 'Not available';
  return printableValue(value);
}

function normaliseMetricValue(label, value) {
  if (/average/i.test(label) && (value === null || value === undefined || Number(value) < 0)) {
    return 'Not available';
  }
  return value ?? 0;
}

function normaliseSummaryCards(summaryCards = []) {
  return summaryCards.map((card) => ({
    ...card,
    value: normaliseMetricValue(card.label, card.value)
  }));
}

function reportSlug(reportName) {
  return reportName.toLowerCase().replaceAll(' ', '-');
}

function buildObservations(summaryCards = [], existingObservations = []) {
  const cardValue = (pattern) => {
    const card = summaryCards.find((item) => pattern.test(item.label));
    const value = Number(card?.value);
    return Number.isFinite(value) ? value : null;
  };
  const totalReferrals = cardValue(/total referrals|received referrals/i);
  const completed = cardValue(/completed referrals/i);
  const pending = cardValue(/pending actions|requiring follow-up|not yet reviewed/i);
  const rejected = cardValue(/rejected referrals/i);
  const feedback = cardValue(/feedback records|feedback received|feedback sent/i);
  const observations = [];

  if (totalReferrals !== null) {
    observations.push(`A total of ${totalReferrals} referral(s) were recorded during the selected period.`);
    if (completed !== null && totalReferrals > 0) {
      observations.push(`${completed} out of ${totalReferrals} referral(s) were completed, giving a ${Math.round((completed / totalReferrals) * 100)}% completion rate.`);
    }
  }
  if (pending !== null) observations.push(pending > 0 ? `${pending} item(s) may require follow-up.` : 'No pending follow-up actions were recorded.');
  if (rejected !== null) observations.push(rejected > 0 ? `${rejected} rejected referral(s) were recorded.` : 'No rejected referrals were recorded during this period.');
  if (feedback !== null) observations.push(`${feedback} feedback record(s) were available for this report.`);

  return [...new Set([...observations, ...existingObservations])].slice(0, 6);
}

function tableColumnsFor(report, section) {
  const title = section.title || '';
  const organisationType = report.generated_by?.organisation_type;
  const rows = section.rows || [];
  const sample = rows[0] || {};
  const has = (key) => Object.prototype.hasOwnProperty.call(sample, key);

  if (/staff users/i.test(title)) {
    return [
      ['full_name', 'Full Name'],
      ['email', 'Email'],
      ['role', 'Role'],
      ['status', 'Status'],
      ['date_added', 'Date Added']
    ];
  }

  if (/referral/i.test(title) && (has('referral_number') || has('referral_id'))) {
    if (has('referred_to_hospital')) {
      return [
        ['referral_number', 'Referral No.'],
        ['client_case_identifier', 'Case No.'],
        ['referred_to_hospital', 'Referred To'],
        ['status', 'Status'],
        ['date_created', 'Referral Date'],
        ['feedback_status', 'Feedback Status']
      ];
    }

    if (has('referred_by_ngo')) {
      return [
        ['referral_id', 'Referral No.'],
        ['client_case_identifier', 'Case No.'],
        ['referred_by_ngo', 'Referred By'],
        ['status', 'Status'],
        ['date_received', 'Referral Date'],
        ['feedback_status', 'Feedback Status']
      ];
    }

    return [
      ['referral_number', 'Referral No.'],
      ['case_number', 'Case No.'],
      [organisationType === 'HOSPITAL' ? 'referred_by' : 'referred_to', organisationType === 'HOSPITAL' ? 'Referred By' : 'Referred To'],
      ['status', 'Status'],
      ['referral_date', 'Referral Date'],
      ['feedback_status', 'Feedback Status']
    ];
  }

  if (/feedback/i.test(title)) {
    if (has('referral_number') || has('hospital') || has('ngo')) {
      return [
        ['referral_number', 'Referral No.'],
        [has('hospital') ? 'hospital' : 'ngo', has('hospital') ? 'Submitted By' : 'Submitted To'],
        ['outcome', 'Outcome'],
        ['feedback_date', 'Date Submitted']
      ];
    }

    return [
      ['total_feedback', 'Total Feedback'],
      ['pending_feedback', 'Pending Feedback'],
      ['submitted_feedback', 'Submitted Feedback']
    ];
  }

  const keys = Object.keys(sample).slice(0, 6);
  return keys.map((key) => [key, humaniseKey(key)]);
}

function emptyStateFor(section) {
  if (/staff users/i.test(section.title)) return 'No staff users found for the selected period.';
  if (/feedback/i.test(section.title)) return 'No feedback exists for the selected period.';
  if (/referral/i.test(section.title)) return 'No referrals found for the selected period.';
  return 'No records found for the selected period.';
}

class PdfReportBuilder {
  constructor(report) {
    this.report = report;
    this.width = 612;
    this.height = 792;
    this.margin = 42;
    this.footerTop = 742;
    this.contentWidth = this.width - this.margin * 2;
    this.pages = [];
    this.page = null;
    this.y = this.margin;
  }

  addPage() {
    this.page = { ops: [] };
    this.pages.push(this.page);
    this.y = this.margin;
    if (this.pages.length > 1) {
      this.drawCompactHeader();
    }
  }

  op(value) {
    this.page.ops.push(value);
  }

  color(hex) {
    const raw = hex.replace('#', '');
    const values = [0, 2, 4].map((index) => parseInt(raw.slice(index, index + 2), 16) / 255);
    return values.map((value) => value.toFixed(3)).join(' ');
  }

  rect(x, y, width, height, fill = null, stroke = null) {
    if (fill) this.op(`${this.color(fill)} rg`);
    if (stroke) this.op(`${this.color(stroke)} RG`);
    this.op(`${x} ${this.height - y - height} ${width} ${height} re ${fill && stroke ? 'B' : fill ? 'f' : 'S'}`);
  }

  text(value, x, y, size = 10, options = {}) {
    const font = options.bold ? 'F2' : 'F1';
    const color = this.color(options.color || '#1f2933');
    this.op(`BT /${font} ${size} Tf ${color} rg ${x} ${this.height - y} Td (${escapePdfText(value)}) Tj ET`);
  }

  line(x1, y1, x2, y2, color = '#d8e2e0') {
    this.op(`${this.color(color)} RG 0.6 w ${x1} ${this.height - y1} m ${x2} ${this.height - y2} l S`);
  }

  wrapText(value, width, size = 9) {
    const maxChars = Math.max(8, Math.floor(width / (size * 0.48)));
    const words = printableValue(value).split(/\s+/);
    const lines = [];
    let current = '';

    for (const word of words) {
      if (!word) continue;
      if ((current ? `${current} ${word}` : word).length > maxChars) {
        if (current) lines.push(current);
        current = word;
      } else {
        current = current ? `${current} ${word}` : word;
      }
    }
    if (current) lines.push(current);
    return lines.length ? lines : [''];
  }

  wrappedText(value, x, y, width, size = 9, options = {}) {
    const lines = this.wrapText(value, width, size);
    lines.forEach((line, index) => this.text(line, x, y + index * (size + 3), size, options));
    return lines.length * (size + 3);
  }

  ensureSpace(heightNeeded) {
    if (!this.page) this.addPage();
    if (this.y + heightNeeded > this.footerTop) {
      this.addPage();
    }
  }

  sectionHeading(title) {
    this.ensureSpace(34);
    this.text(title, this.margin, this.y, 14, { bold: true, color: '#173f3a' });
    this.line(this.margin, this.y + 8, this.margin + this.contentWidth, this.y + 8);
    this.y += 26;
  }

  drawCompactHeader() {
    this.rect(this.margin, this.margin, this.contentWidth, 34, '#f2f7f6', '#d8e2e0');
    this.text('ReferralLink', this.margin + 12, this.margin + 20, 12, { bold: true, color: '#0f766e' });
    this.text(this.report.report_name, this.margin + 118, this.margin + 20, 11, { bold: true, color: '#24343d' });
    this.y = this.margin + 52;
  }

  drawReportHeader() {
    this.addPage();
    this.rect(this.margin, this.margin, this.contentWidth, 118, '#edf8f6', '#cbdedb');
    this.text('ReferralLink', this.margin + 18, this.margin + 28, 18, { bold: true, color: '#0f766e' });
    this.text(this.report.report_name, this.margin + 18, this.margin + 58, 22, { bold: true, color: '#17252a' });

    const metadata = [
      ['Generated by', this.report.generated_by?.name || 'Current user'],
      ['User role', formatRole(this.report.generated_by?.role)],
      ['Organisation', this.report.generated_by?.organisation || 'Platform'],
      ['Date generated', formatReportDate(this.report.generated_at, true)]
    ];

    metadata.forEach(([label, value], index) => {
      const x = this.margin + 300;
      const y = this.margin + 26 + index * 20;
      this.text(label, x, y, 8, { bold: true, color: '#61737a' });
      this.text(value, x + 96, y, 9, { color: '#1f2933' });
    });

    this.y = this.margin + 142;
  }

  drawFilters() {
    this.sectionHeading('Selected filters');
    const entries = Object.entries(this.report.filters_applied || {});
    const rowHeight = 28;
    const height = Math.max(44, entries.length * rowHeight + 16);
    this.ensureSpace(height);
    this.rect(this.margin, this.y, this.contentWidth, height, '#fbfdfd', '#d8e2e0');
    entries.forEach(([key, value], index) => {
      const y = this.y + 20 + index * rowHeight;
      this.text(humaniseKey(key), this.margin + 14, y, 8, { bold: true, color: '#61737a' });
      this.text(formatReportValue(key, value), this.margin + 150, y, 10, { color: '#1f2933' });
    });
    this.y += height + 18;
  }

  drawSummaryCards() {
    this.sectionHeading('Executive summary');
    const cardsToDraw = this.report.summary_cards || [];
    const gap = 10;
    const columns = 3;
    const cardWidth = (this.contentWidth - gap * (columns - 1)) / columns;
    const cardHeight = 58;

    cardsToDraw.forEach((card, index) => {
      if (index % columns === 0) this.ensureSpace(cardHeight + 8);
      const column = index % columns;
      const x = this.margin + column * (cardWidth + gap);
      const y = this.y + Math.floor(index / columns) * (cardHeight + 8);
      this.rect(x, y, cardWidth, cardHeight, '#f8fbfb', '#d8e2e0');
      this.wrappedText(card.label, x + 12, y + 18, cardWidth - 24, 8, { bold: true, color: '#61737a' });
      this.wrappedText(formatReportValue(card.label, card.value), x + 12, y + 42, cardWidth - 24, 15, { bold: true, color: '#173f3a' });
    });

    this.y += Math.ceil(cardsToDraw.length / columns) * (cardHeight + 8) + 14;
  }

  drawCharts() {
    const charts = (this.report.charts || []).filter((chart) => chart.rows?.some((row) => Number(row.total || 0) > 0));
    if (!charts.length) return;
    this.sectionHeading('Visual analysis');

    charts.forEach((chart) => {
      const rows = chart.rows.slice(0, 12);
      const barWidth = 30;
      const chartWidth = rows.length * (barWidth + 8) + 20;
      const chartHeight = 180;
      const padding = { top: 10, bottom: 40, left: 30, right: 10 };
      const maxWidth = this.contentWidth;
      
      const width = Math.min(chartWidth, maxWidth);
      const height = chartHeight + padding.top + padding.bottom;
      
      this.ensureSpace(height + 20);
      
      // Draw chart border
      this.rect(this.margin, this.y, maxWidth, height, '#ffffff', '#d8e2e0');
      this.text(chart.title, this.margin + 12, this.y + 20, 11, { bold: true, color: '#24343d' });
      
      const max = Math.max(...rows.map((row) => Number(row.total || 0)), 1);
      const availableWidth = Math.min(width - padding.left - padding.right, maxWidth - 24);
      const scaledBarWidth = Math.max(8, availableWidth / rows.length - 4);
      const scaledChartHeight = chartHeight - padding.top - padding.bottom;
      
      // Draw Y-axis labels
      const yLabelCount = 4;
      for (let i = 0; i <= yLabelCount; i++) {
        const ratio = i / yLabelCount;
        const value = Math.round(max * ratio);
        const y = this.y + padding.top + chartHeight - ratio * scaledChartHeight;
        this.text(String(value), this.margin + padding.left - 8, y + 2, 7, { 
          color: '#666', 
          align: 'right'
        });
      }
      
      // Draw bars
      rows.forEach((row, index) => {
        const value = Number(row.total || 0);
        const barHeight = (value / max) * scaledChartHeight;
        const x = this.margin + padding.left + index * (scaledBarWidth + 4);
        const barY = this.y + padding.top + chartHeight - barHeight;
        
        // Draw bar
        this.rect(x, barY, scaledBarWidth, barHeight, '#0f766e');
        
        // Draw value on top of bar
        if (value > 0) {
          this.text(String(value), x + scaledBarWidth / 2, barY - 3, 7, {
            bold: true,
            color: '#0f766e'
          });
        }
        
        // Draw label below bar
        const labelY = this.y + padding.top + chartHeight + 8;
        const labelLines = this.wrapText(row.label, scaledBarWidth + 4, 6);
        labelLines.forEach((line, lineIndex) => {
          this.text(line, x + 2, labelY + lineIndex * 7, 6, {
            color: '#394c54'
          });
        });
      });
      
      this.y += height + 14;
    });
  }

  drawTable(section) {
    const rows = section.rows || [];
    this.sectionHeading(section.title || 'Report table');
    if (!rows.length) {
      this.ensureSpace(40);
      this.rect(this.margin, this.y, this.contentWidth, 36, '#fbfdfd', '#d8e2e0');
      this.text(emptyStateFor(section), this.margin + 12, this.y + 22, 10, { color: '#61737a' });
      this.y += 52;
      return;
    }

    const columns = tableColumnsFor(this.report, section).filter(([key]) => rows.some((row) => row[key] !== undefined));
    if (!columns.length) return;

    const colWidth = this.contentWidth / columns.length;
    const drawHeader = () => {
      this.ensureSpace(28);
      this.rect(this.margin, this.y, this.contentWidth, 24, '#e9f5f4', '#cbdedb');
      columns.forEach(([, label], index) => this.wrappedText(label, this.margin + index * colWidth + 6, this.y + 16, colWidth - 12, 8, { bold: true, color: '#173f3a' }));
      this.y += 24;
    };

    drawHeader();
    rows.slice(0, 120).forEach((row, rowIndex) => {
      const cellLines = columns.map(([key]) => this.wrapText(formatReportValue(key, row[key]), colWidth - 12, 7));
      const rowHeight = Math.max(24, Math.max(...cellLines.map((lines) => lines.length)) * 10 + 10);
      if (this.y + rowHeight > this.footerTop) {
        this.addPage();
        drawHeader();
      }
      this.rect(this.margin, this.y, this.contentWidth, rowHeight, rowIndex % 2 === 0 ? '#ffffff' : '#f8fbfb', '#edf2f4');
      columns.forEach(([key], index) => {
        this.wrappedText(formatReportValue(key, row[key]), this.margin + index * colWidth + 6, this.y + 14, colWidth - 12, 7, { color: '#24343d' });
      });
      this.y += rowHeight;
    });

    if (rows.length > 120) {
      this.ensureSpace(24);
      this.text(`${rows.length - 120} additional row(s) omitted from the PDF view. Use CSV for the full data export.`, this.margin, this.y + 16, 9, { color: '#61737a' });
      this.y += 32;
    } else {
      this.y += 16;
    }
  }

  drawObservations() {
    if (!this.report.observations?.length) return;
    this.sectionHeading('Observations');
    this.report.observations.forEach((item) => {
      const height = this.wrapText(item, this.contentWidth - 28, 10).length * 13 + 14;
      this.ensureSpace(height);
      this.rect(this.margin, this.y, this.contentWidth, height, '#fbfdfd', '#d8e2e0');
      this.text('-', this.margin + 12, this.y + 20, 10, { bold: true, color: '#0f766e' });
      this.wrappedText(item, this.margin + 28, this.y + 20, this.contentWidth - 42, 10, { color: '#24343d' });
      this.y += height + 8;
    });
  }

  drawDisclaimer() {
    this.ensureSpace(56);
    this.rect(this.margin, this.y, this.contentWidth, 42, '#f8fbfb', '#d8e2e0');
    this.wrappedText('This report was automatically generated by ReferralLink based on records available in the system at the time of generation.', this.margin + 12, this.y + 22, this.contentWidth - 24, 8, { color: '#61737a' });
    this.y += 56;
  }

  addFooters() {
    const total = this.pages.length;
    this.pages.forEach((page, index) => {
      const footerY = 768;
      page.ops.push(`${this.color('#d8e2e0')} RG 0.5 w ${this.margin} ${this.height - 748} m ${this.margin + this.contentWidth} ${this.height - 748} l S`);
      page.ops.push(`BT /F1 8 Tf ${this.color('#61737a')} rg ${this.margin} ${this.height - footerY} Td (${escapePdfText('ReferralLink')}) Tj ET`);
      page.ops.push(`BT /F1 8 Tf ${this.color('#61737a')} rg ${this.margin + 160} ${this.height - footerY} Td (${escapePdfText(this.report.report_name)}) Tj ET`);
      page.ops.push(`BT /F1 8 Tf ${this.color('#61737a')} rg ${this.margin + this.contentWidth - 70} ${this.height - footerY} Td (${escapePdfText(`Page ${index + 1} of ${total}`)}) Tj ET`);
    });
  }

  render() {
    this.drawReportHeader();
    this.drawFilters();
    this.drawSummaryCards();
    this.drawCharts();
    (this.report.sections || []).forEach((sectionItem) => this.drawTable(sectionItem));
    this.drawObservations();
    this.drawDisclaimer();
    this.addFooters();
    return createPdfBase64(this.pages, this.width, this.height);
  }
}

function createPdfBase64(pages, width = 612, height = 792) {
  const pageIds = pages.map((_, index) => 5 + index * 2);
  const contentIds = pages.map((_, index) => 6 + index * 2);
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'
  ];

  pages.forEach((page, index) => {
    const stream = page.ops.join('\n');
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentIds[index]} 0 R >>`);
    objects.push(`<< /Length ${Buffer.byteLength(stream, 'latin1')} >>\nstream\n${stream}\nendstream`);
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'latin1').toString('base64');
}

export function pdfPayload(report) {
  const builder = new PdfReportBuilder(report);
  return {
    file_url: `data:application/pdf;base64,${builder.render()}`,
    file_name: `${reportSlug(report.report_name)}.pdf`
  };
}

function generatedBy(user) {
  return {
    name: user.full_name,
    email: user.email,
    role: user.role,
    organisation: user.organisation_name || null,
    organisation_type: user.organisation_type || null
  };
}

function selectedFilters(filters, user) {
  const selected = {
    date_range: filters.start_date || filters.end_date ? `${filters.start_date || 'Beginning'} to ${filters.end_date || 'Today'}` : 'All time'
  };

  if (user.role === ROLES.PLATFORM_ADMIN) {
    selected.organisation_filter = filters.organisation_id || 'All organisations';
  } else {
    // Operational and organisation-admin reports are always constrained by the authenticated user's organisation.
    selected.organisation_scope = user.organisation_name || 'Assigned organisation';
  }

  return selected;
}

function insight(text) {
  return text;
}

async function auditReport(user, reportType, filters, outputFormat, success, message = null) {
  try {
    await query(
      `INSERT INTO audit_logs (user_id, action, entity_type, entity_id, details)
       VALUES (:user_id, 'GENERATE_REPORT', 'report', NULL,
         JSON_OBJECT('organisation_id', :organisation_id, 'role', :role, 'report_type', :report_type,
                     'filters', :filters, 'output_format', :output_format, 'success', :success, 'message', :message))`,
      {
        user_id: user.id,
        organisation_id: user.organisation_id || null,
        role: user.role,
        report_type: reportType,
        filters: JSON.stringify(sanitizeFilters(filters)),
        output_format: outputFormat,
        success,
        message
      }
    );
  } catch (error) {
    console.error('Could not write report audit log', error);
  }
}

async function platformSystemOverview(user, filters) {
  const params = filterParams(filters, user);
  const orgWhere = `(:organisation_id IS NULL OR o.id = :organisation_id) AND ${dateClause('o')}`;
  const referralWhere = `(:organisation_id IS NULL OR r.referring_organisation_id = :organisation_id OR r.receiving_organisation_id = :organisation_id)
                         AND ${dateClause('r')}`;

  const [orgTotals, usersByRole, referralTotals, feedbackTotals, orgGrowth, orgStatus] = await Promise.all([
    query(
      `SELECT COUNT(*) AS total_organisations,
              SUM(CASE WHEN type = 'NGO' THEN 1 ELSE 0 END) AS total_ngos,
              SUM(CASE WHEN type = 'HOSPITAL' THEN 1 ELSE 0 END) AS total_hospitals,
              SUM(CASE WHEN status = 'ACTIVE' THEN 1 ELSE 0 END) AS active_organisations,
              SUM(CASE WHEN status != 'ACTIVE' THEN 1 ELSE 0 END) AS inactive_organisations
       FROM organisations o
       WHERE ${orgWhere}`,
      params
    ),
    query(
      `SELECT u.role, COUNT(*) AS total_users
       FROM users u
       LEFT JOIN organisations o ON o.id = u.organisation_id
       WHERE (:organisation_id IS NULL OR u.organisation_id = :organisation_id)
         AND (:start_date IS NULL OR DATE(u.created_at) >= :start_date)
         AND (:end_date IS NULL OR DATE(u.created_at) <= :end_date)
       GROUP BY u.role
       ORDER BY total_users DESC`,
      params
    ),
    query(`SELECT COUNT(*) AS total_referrals FROM referrals r WHERE ${referralWhere}`, params),
    query(
      `SELECT COUNT(f.id) AS total_feedback
       FROM feedback f
       JOIN referrals r ON r.id = f.referral_id
       WHERE ${referralWhere}`,
      params
    ),
    query(
      `SELECT DATE_FORMAT(o.created_at, '%Y-%m') AS month, o.type AS organisation_type, COUNT(*) AS organisations_registered
       FROM organisations o
       WHERE ${orgWhere}
       GROUP BY DATE_FORMAT(o.created_at, '%Y-%m'), o.type
       ORDER BY month`,
      params
    ),
    query(
      `SELECT o.status AS organisation_status, COUNT(*) AS total
       FROM organisations o
       WHERE ${orgWhere}
       GROUP BY o.status`,
      params
    )
  ]);

  const totals = orgTotals[0] || {};
  const totalUsers = usersByRole.reduce((sum, row) => sum + Number(row.total_users || 0), 0);
  const summaryCards = cards([
    ['Total NGOs', totals.total_ngos],
    ['Total hospitals', totals.total_hospitals],
    ['Total organisations', totals.total_organisations],
    ['Active organisations', totals.active_organisations],
    ['Inactive organisations', totals.inactive_organisations],
    ['Total users', totalUsers],
    ['Total referrals', referralTotals[0]?.total_referrals],
    ['Total feedback records', feedbackTotals[0]?.total_feedback]
  ]);

  return {
    summary_cards: summaryCards,
    charts: [
      { title: 'Organisations by type', rows: [{ label: 'NGO', total: totals.total_ngos || 0 }, { label: 'Hospital', total: totals.total_hospitals || 0 }] },
      { title: 'Users by role', rows: usersByRole.map((row) => ({ label: row.role, total: row.total_users })) },
      { title: 'Organisation status', rows: orgStatus.map((row) => ({ label: row.organisation_status, total: row.total })) }
    ],
    sections: [
      section('High-level system metrics', summaryCards.map((card) => ({ metric: card.label, value: card.value }))),
      section('Users by role', usersByRole),
      section('Organisation growth trend', orgGrowth)
    ],
    observations: [
      totalUsers ? insight(`${totalUsers} user account(s) matched the selected filters.`) : insight('No users matched the selected filters.'),
      referralTotals[0]?.total_referrals ? insight('Referral activity exists for the selected period.') : insight('No referrals were recorded in the selected period.')
    ]
  };
}

async function platformOrganisationReport(user, filters) {
  const params = filterParams(filters, user);
  const rows = await query(
    `SELECT o.id,
            o.name AS organisation_name,
            o.type AS organisation_type,
            SUBSTRING_INDEX(o.email, '@', -1) AS email_domain,
            o.email AS contact_email,
            o.phone,
            o.location,
            o.status,
            DATE(o.created_at) AS date_registered,
            (SELECT COUNT(*) FROM users u WHERE u.organisation_id = o.id) AS total_users,
            (SELECT COUNT(*) FROM users u WHERE u.organisation_id = o.id AND u.role = 'ORG_ADMIN') AS organisation_admins,
            (SELECT COUNT(*) FROM users u WHERE u.organisation_id = o.id AND u.role != 'ORG_ADMIN') AS staff_users,
            (SELECT COUNT(*) FROM referrals r WHERE (r.referring_organisation_id = o.id OR r.receiving_organisation_id = o.id)
              AND (:start_date IS NULL OR DATE(r.created_at) >= :start_date)
              AND (:end_date IS NULL OR DATE(r.created_at) <= :end_date)) AS referral_activity_count
     FROM organisations o
     WHERE (:organisation_id IS NULL OR o.id = :organisation_id)
       AND ${dateClause('o')}
     ORDER BY o.type, o.name`,
    params
  );

  const totalUsers = rows.reduce((sum, row) => sum + Number(row.total_users || 0), 0);
  return {
    summary_cards: cards([
      ['Organisations listed', rows.length],
      ['Total users', totalUsers],
      ['Organisation admins', rows.reduce((sum, row) => sum + Number(row.organisation_admins || 0), 0)],
      ['Referral activity count', rows.reduce((sum, row) => sum + Number(row.referral_activity_count || 0), 0)]
    ]),
    charts: [
      { title: 'Organisations by type', rows: Object.values(rows.reduce((acc, row) => {
        acc[row.organisation_type] ||= { label: row.organisation_type, total: 0 };
        acc[row.organisation_type].total += 1;
        return acc;
      }, {})) },
      { title: 'Users per organisation', rows: rows.map((row) => ({ label: row.organisation_name, total: row.total_users })) }
    ],
    sections: [section('Organisation directory', rows)],
    observations: [
      rows.length ? insight(`${rows.length} organisation record(s) matched the selected filters.`) : insight('No organisations matched the selected filters.')
    ]
  };
}

async function organisationActivityReport(user, filters) {
  const params = filterParams(filters, user);
  const sideColumn = user.organisation_type === 'NGO' ? 'r.referring_organisation_id' : 'r.receiving_organisation_id';

  const [profile, staff, referralStatus, referralTrend, referrals, feedback, performance] = await Promise.all([
    query('SELECT name, type, email, phone, location, status, DATE(created_at) AS date_registered FROM organisations WHERE id = :current_organisation_id', params),
    query(
      `SELECT full_name, email, role, status, DATE(created_at) AS date_added
       FROM users
       WHERE organisation_id = :current_organisation_id
         AND (:start_date IS NULL OR DATE(created_at) >= :start_date)
         AND (:end_date IS NULL OR DATE(created_at) <= :end_date)
       ORDER BY full_name`,
      params
    ),
    query(
      `SELECT r.status, COUNT(*) AS total
       FROM referrals r
       WHERE ${sideColumn} = :current_organisation_id AND ${dateClause('r')}
       GROUP BY r.status`,
      params
    ),
    query(
      `SELECT DATE_FORMAT(r.created_at, '%Y-%m') AS month, COUNT(*) AS total
       FROM referrals r
       WHERE ${sideColumn} = :current_organisation_id AND ${dateClause('r')}
       GROUP BY DATE_FORMAT(r.created_at, '%Y-%m')
       ORDER BY month`,
      params
    ),
    query(
      `SELECT r.referral_number, b.case_number, ref_org.name AS referred_by, rec_org.name AS referred_to,
              r.status, DATE(r.created_at) AS referral_date,
              CASE WHEN f.id IS NULL THEN 'PENDING' ELSE 'SUBMITTED' END AS feedback_status
       FROM referrals r
       JOIN beneficiaries b ON b.id = r.beneficiary_id
       JOIN organisations ref_org ON ref_org.id = r.referring_organisation_id
       JOIN organisations rec_org ON rec_org.id = r.receiving_organisation_id
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE ${sideColumn} = :current_organisation_id AND ${dateClause('r')}
       ORDER BY r.created_at DESC
       LIMIT 100`,
      params
    ),
    query(
      `SELECT COUNT(f.id) AS total_feedback,
              SUM(CASE WHEN f.id IS NULL AND r.status = 'Completed' THEN 1 ELSE 0 END) AS pending_feedback,
              SUM(CASE WHEN f.id IS NOT NULL THEN 1 ELSE 0 END) AS submitted_feedback
       FROM referrals r
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE ${sideColumn} = :current_organisation_id AND ${dateClause('r')}`,
      params
    ),
    query(
      `SELECT SUM(CASE WHEN r.status IN ('Pending', 'Accepted', 'In Progress') THEN 1 ELSE 0 END) AS pending_actions,
              SUM(CASE WHEN r.status = 'Completed' THEN 1 ELSE 0 END) AS completed_referrals,
              SUM(CASE WHEN r.status = 'Rejected' THEN 1 ELSE 0 END) AS rejected_referrals,
              ROUND(AVG(CASE
                WHEN COALESCE(r.completed_at, r.accepted_at, r.updated_at) >= r.created_at
                THEN TIMESTAMPDIFF(HOUR, r.created_at, COALESCE(r.completed_at, r.accepted_at, r.updated_at))
                ELSE NULL
              END), 1) AS average_response_hours
       FROM referrals r
       WHERE ${sideColumn} = :current_organisation_id AND ${dateClause('r')}`,
      params
    )
  ]);

  const feedbackSummary = feedback[0] || {};
  const performanceSummary = performance[0] || {};
  return {
    summary_cards: cards([
      ['Staff users', staff.length],
      ['Total referrals', referrals.length],
      ['Feedback records', feedbackSummary.total_feedback],
      ['Pending actions', performanceSummary.pending_actions],
      ['Completed referrals', performanceSummary.completed_referrals],
      ['Rejected referrals', performanceSummary.rejected_referrals],
      ['Average response hours', performanceSummary.average_response_hours ?? 'Not available']
    ]),
    charts: [
      { title: 'Referral statuses', rows: referralStatus.map((row) => ({ label: row.status, total: row.total })) },
      { title: 'Referrals over time', rows: referralTrend.map((row) => ({ label: row.month, total: row.total })) },
      { title: 'Feedback status', rows: [{ label: 'Pending', total: feedbackSummary.pending_feedback || 0 }, { label: 'Submitted', total: feedbackSummary.submitted_feedback || 0 }] }
    ],
    sections: [
      section('Organisation profile summary', profile),
      section('Staff users', staff),
      section('Referral summary', referrals),
      section('Feedback summary', [feedbackSummary]),
      section('Performance summary', [performanceSummary])
    ],
    observations: [
      referrals.length ? insight(`${referrals.length} referral(s) matched the selected period.`) : insight('No referrals were recorded in the selected period.'),
      Number(feedbackSummary.pending_feedback || 0) > 0 ? insight('Some completed referrals still have pending feedback.') : insight('No completed referrals are waiting for feedback.')
    ]
  };
}

async function ngoSocialWorkerReport(user, filters) {
  const params = filterParams(filters, user);

  const [referralStatus, byHospital, trend, cases, referrals, feedback, followUp] = await Promise.all([
    query(
      `SELECT r.status, COUNT(*) AS total
       FROM referrals r
       WHERE r.referring_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY r.status`,
      params
    ),
    query(
      `SELECT rec_org.name AS hospital, COUNT(*) AS total
       FROM referrals r
       JOIN organisations rec_org ON rec_org.id = r.receiving_organisation_id
       WHERE r.referring_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY rec_org.id, rec_org.name
       ORDER BY total DESC`,
      params
    ),
    query(
      `SELECT DATE_FORMAT(r.created_at, '%Y-%m') AS month, COUNT(*) AS total
       FROM referrals r
       WHERE r.referring_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY DATE_FORMAT(r.created_at, '%Y-%m')
       ORDER BY month`,
      params
    ),
    query(
      `SELECT b.case_number, b.full_name, b.gender, b.county, b.location, DATE(b.created_at) AS date_created,
              COUNT(r.id) AS referral_count
       FROM beneficiaries b
       LEFT JOIN referrals r ON r.beneficiary_id = b.id
       WHERE b.organisation_id = :current_organisation_id
         AND (:start_date IS NULL OR DATE(b.created_at) >= :start_date)
         AND (:end_date IS NULL OR DATE(b.created_at) <= :end_date)
       GROUP BY b.id
       ORDER BY b.created_at DESC`,
      params
    ),
    query(
      `SELECT r.referral_number, b.case_number AS client_case_identifier, rec_org.name AS referred_to_hospital,
              r.status, DATE(r.created_at) AS date_created,
              CASE WHEN f.id IS NULL THEN 'PENDING' ELSE 'SUBMITTED' END AS feedback_status
       FROM referrals r
       JOIN beneficiaries b ON b.id = r.beneficiary_id
       JOIN organisations rec_org ON rec_org.id = r.receiving_organisation_id
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE r.referring_organisation_id = :current_organisation_id AND ${dateClause('r')}
       ORDER BY r.created_at DESC`,
      params
    ),
    query(
      `SELECT rec_org.name AS hospital, r.referral_number, f.outcome, DATE(f.submitted_at) AS feedback_date
       FROM feedback f
       JOIN referrals r ON r.id = f.referral_id
       JOIN organisations rec_org ON rec_org.id = r.receiving_organisation_id
       WHERE r.referring_organisation_id = :current_organisation_id
         AND (:start_date IS NULL OR DATE(f.submitted_at) >= :start_date)
         AND (:end_date IS NULL OR DATE(f.submitted_at) <= :end_date)
       ORDER BY f.submitted_at DESC`,
      params
    ),
    query(
      `SELECT SUM(CASE WHEN f.id IS NULL THEN 1 ELSE 0 END) AS referrals_with_no_feedback,
              SUM(CASE WHEN r.status IN ('Pending', 'Accepted', 'In Progress') THEN 1 ELSE 0 END) AS requiring_follow_up,
              SUM(CASE WHEN r.status != 'Completed' AND DATEDIFF(CURDATE(), r.created_at) > 7 THEN 1 ELSE 0 END) AS delayed_unresolved_referrals
       FROM referrals r
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE r.referring_organisation_id = :current_organisation_id AND ${dateClause('r')}`,
      params
    )
  ]);

  const followUpSummary = followUp[0] || {};
  return {
    summary_cards: cards([
      ['Total referrals', referrals.length],
      ['Case profiles', cases.length],
      ['Feedback received', feedback.length],
      ['No feedback yet', followUpSummary.referrals_with_no_feedback],
      ['Requiring follow-up', followUpSummary.requiring_follow_up],
      ['Delayed unresolved', followUpSummary.delayed_unresolved_referrals]
    ]),
    charts: [
      { title: 'Referrals by status', rows: referralStatus.map((row) => ({ label: row.status, total: row.total })) },
      { title: 'Referrals by hospital', rows: byHospital.map((row) => ({ label: row.hospital, total: row.total })) },
      { title: 'Referrals over time', rows: trend.map((row) => ({ label: row.month, total: row.total })) }
    ],
    sections: [
      section('Referral table', referrals),
      section('Case profile summary', cases),
      section('Hospital feedback summary', feedback),
      section('Follow-up summary', [followUpSummary])
    ],
    observations: [
      referrals.length ? insight(`${referrals.length} referral(s) were created for the assigned NGO.`) : insight('No referrals were recorded in the selected period.'),
      Number(followUpSummary.referrals_with_no_feedback || 0) > 0 ? insight('Some referrals still have no hospital feedback.') : insight('All matching referrals have feedback recorded.')
    ]
  };
}

async function hospitalRecordsKeeperReport(user, filters) {
  const params = filterParams(filters, user);

  const [statusRows, byNgo, trend, referrals, feedback, pending, completion, rejected] = await Promise.all([
    query(
      `SELECT r.status, COUNT(*) AS total
       FROM referrals r
       WHERE r.receiving_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY r.status`,
      params
    ),
    query(
      `SELECT ref_org.name AS referring_ngo, COUNT(*) AS total
       FROM referrals r
       JOIN organisations ref_org ON ref_org.id = r.referring_organisation_id
       WHERE r.receiving_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY ref_org.id, ref_org.name
       ORDER BY total DESC`,
      params
    ),
    query(
      `SELECT DATE_FORMAT(r.created_at, '%Y-%m') AS month, COUNT(*) AS total
       FROM referrals r
       WHERE r.receiving_organisation_id = :current_organisation_id AND ${dateClause('r')}
       GROUP BY DATE_FORMAT(r.created_at, '%Y-%m')
       ORDER BY month`,
      params
    ),
    query(
      `SELECT r.referral_number AS referral_id, b.case_number AS client_case_identifier, ref_org.name AS referred_by_ngo,
              r.status, DATE(r.created_at) AS date_received,
              CASE WHEN f.id IS NULL THEN 'PENDING' ELSE 'SUBMITTED' END AS feedback_status
       FROM referrals r
       JOIN beneficiaries b ON b.id = r.beneficiary_id
       JOIN organisations ref_org ON ref_org.id = r.referring_organisation_id
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE r.receiving_organisation_id = :current_organisation_id AND ${dateClause('r')}
       ORDER BY r.created_at DESC`,
      params
    ),
    query(
      `SELECT r.referral_number, ref_org.name AS ngo, f.outcome, DATE(f.submitted_at) AS feedback_date
       FROM feedback f
       JOIN referrals r ON r.id = f.referral_id
       JOIN organisations ref_org ON ref_org.id = r.referring_organisation_id
       WHERE r.receiving_organisation_id = :current_organisation_id
         AND (:start_date IS NULL OR DATE(f.submitted_at) >= :start_date)
         AND (:end_date IS NULL OR DATE(f.submitted_at) <= :end_date)
       ORDER BY f.submitted_at DESC`,
      params
    ),
    query(
      `SELECT SUM(CASE WHEN r.status = 'Pending' THEN 1 ELSE 0 END) AS not_yet_reviewed,
              SUM(CASE WHEN r.status = 'Completed' AND f.id IS NULL THEN 1 ELSE 0 END) AS waiting_for_feedback,
              SUM(CASE WHEN r.status IN ('Pending', 'Accepted', 'In Progress') THEN 1 ELSE 0 END) AS requiring_hospital_action
       FROM referrals r
       LEFT JOIN feedback f ON f.referral_id = r.id
       WHERE r.receiving_organisation_id = :current_organisation_id AND ${dateClause('r')}`,
      params
    ),
    query(
      `SELECT COUNT(*) AS completed_referrals,
              ROUND(AVG(CASE
                WHEN COALESCE(r.completed_at, r.updated_at) >= r.created_at
                THEN TIMESTAMPDIFF(HOUR, r.created_at, COALESCE(r.completed_at, r.updated_at))
                ELSE NULL
              END), 1) AS average_completion_hours
       FROM referrals r
       WHERE r.receiving_organisation_id = :current_organisation_id
         AND r.status = 'Completed'
         AND ${dateClause('r')}`,
      params
    ),
    query(
      `SELECT r.referral_number, ref_org.name AS referring_ngo, DATE(r.updated_at) AS rejection_date, r.reason AS referral_reason
       FROM referrals r
       JOIN organisations ref_org ON ref_org.id = r.referring_organisation_id
       WHERE r.receiving_organisation_id = :current_organisation_id
         AND r.status = 'Rejected'
         AND ${dateClause('r')}
       ORDER BY r.updated_at DESC`,
      params
    )
  ]);

  const pendingSummary = pending[0] || {};
  const completionSummary = completion[0] || {};
  return {
    summary_cards: cards([
      ['Received referrals', referrals.length],
      ['Feedback sent', feedback.length],
      ['Not yet reviewed', pendingSummary.not_yet_reviewed],
      ['Waiting for feedback', pendingSummary.waiting_for_feedback],
      ['Completed referrals', completionSummary.completed_referrals],
      ['Average completion hours', completionSummary.average_completion_hours ?? 'Not available'],
      ['Rejected referrals', rejected.length]
    ]),
    charts: [
      { title: 'Referrals by status', rows: statusRows.map((row) => ({ label: row.status, total: row.total })) },
      { title: 'Referrals by referring NGO', rows: byNgo.map((row) => ({ label: row.referring_ngo, total: row.total })) },
      { title: 'Referrals over time', rows: trend.map((row) => ({ label: row.month, total: row.total })) }
    ],
    sections: [
      section('Received referrals', referrals),
      section('Feedback given', feedback),
      section('Pending action summary', [pendingSummary]),
      section('Completion summary', [completionSummary]),
      section('Rejection summary', rejected)
    ],
    observations: [
      referrals.length ? insight(`${referrals.length} referral(s) were received by the assigned hospital.`) : insight('No referrals were received in the selected period.'),
      Number(pendingSummary.requiring_hospital_action || 0) > 0 ? insight('Some referrals still require hospital action.') : insight('No matching referrals currently require hospital action.')
    ]
  };
}

async function generateReportData(report, user, filters) {
  if (report.report_key === 'platform_system_overview') return platformSystemOverview(user, filters);
  if (report.report_key === 'platform_organisation') return platformOrganisationReport(user, filters);
  if (report.report_key === 'organisation_activity') return organisationActivityReport(user, filters);
  if (report.report_key === 'ngo_social_worker_activity') return ngoSocialWorkerReport(user, filters);
  if (report.report_key === 'hospital_records_keeper_activity') return hospitalRecordsKeeperReport(user, filters);
  return { summary_cards: [], charts: [], sections: [], observations: [] };
}

async function buildReportResponse(report, user, filters, outputFormat) {
  const generatedAt = new Date().toISOString();
  const data = await generateReportData(report, user, filters);
  const summaryCards = normaliseSummaryCards(data.summary_cards);
  const response = {
    report_key: report.report_key,
    report_name: report.report_name,
    generated_at: generatedAt,
    generated_by: generatedBy(user),
    filters_applied: selectedFilters(filters, user),
    output_format: outputFormat,
    summary_cards: summaryCards,
    charts: data.charts,
    sections: data.sections,
    observations: buildObservations(summaryCards, data.observations),
    summary: { total_records: data.sections.reduce((sum, item) => sum + (item.rows?.length || 0), 0) },
    rows: data.sections[0]?.rows || []
  };

  if (outputFormat === 'csv') {
    Object.assign(response, csvPayload(response));
  }

  if (outputFormat === 'pdf') {
    Object.assign(response, pdfPayload(response));
  }

  return response;
}

reportsRouter.get('/available', requireAuth, (req, res) => {
  res.json({
    reports: availableReportsFor(req.user),
    output_formats: Object.entries(formatLabels).map(([value, label]) => ({ value, label }))
  });
});

reportsRouter.post('/generate', requireAuth, asyncHandler(async (req, res) => {
  const fallbackReport = defaultReportForUser(req.user);
  const reportType = req.body.report_type || fallbackReport?.report_key;
  const filters = sanitizeFilters(req.body.filters || {});
  const outputFormat = req.body.output_format || 'screen';

  try {
    const report = validateReportRequest(req.user, reportType, filters, outputFormat);
    const response = await buildReportResponse(report, req.user, filters, outputFormat);
    await auditReport(req.user, reportType, filters, outputFormat, true);
    return res.json(response);
  } catch (error) {
    await auditReport(req.user, reportType || 'unknown', filters, outputFormat, false, error.message);
    throw error;
  }
}));

reportsRouter.get('/summary', requireAuth, asyncHandler(async (req, res) => {
  const report = defaultReportForUser(req.user);
  if (!report) {
    return res.json({ mode: 'empty', statuses: [], hospitals: [], outcomes: [], averageResponseHours: 0 });
  }

  const generated = await buildReportResponse(report, req.user, {}, 'screen');
  res.json({
    mode: req.user.role === ROLES.PLATFORM_ADMIN ? 'platform' : req.user.role === ROLES.ORG_ADMIN ? 'organisation' : 'operational',
    statuses: (generated.charts[0]?.rows || []).slice(0, 4).map((row) => ({ label: row.label || 'Records', total: row.total || 0 })),
    hospitals: [],
    outcomes: [],
    averageResponseHours: 0
  });
}));
