-- Reference note:
-- Use `npm run db:seed` to load demo data.
-- The seed script generates bcrypt password hashes at runtime and creates:
--   platform@demo.test
--   orgadmin@demo.test
--   ngo@demo.test
--   hospital@demo.test
--   hospitaladmin@demo.test
-- All demo accounts use password123.
